DROP TABLE  CLIENT_ADRESSE
DROP TABLE COMMANDE_ITEM
DROP TABLE ITEM
DROP TABLE COMMANDE
DROP TABLE ADRESSE
DROP TABLE CLIENT


CREATE TABLE CLIENT (ID INTEGER NOT NULL, MAIL VARCHAR(255), NOM VARCHAR(255), PRENOM VARCHAR(255), TELEPHONE VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE ADRESSE (ID INTEGER NOT NULL, CP VARCHAR(255), NUM INTEGER, PAYS VARCHAR(255), VOIE VARCHAR(255), VOIETYPE VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE COMMANDE (ID INTEGER NOT NULL, DATE DATE, ADRESSE_ID INTEGER, CLIENT_ID INTEGER, PRIMARY KEY (ID))
CREATE TABLE ITEM (ID INTEGER NOT NULL, LABEL VARCHAR(255), SIZE INTEGER, WEIGHT INTEGER, PRIMARY KEY (ID))
CREATE TABLE COMMANDE_ITEM (Commande_ID INTEGER NOT NULL, items_ID INTEGER NOT NULL, PRIMARY KEY (Commande_ID, items_ID))
CREATE TABLE CLIENT_ADRESSE (Client_ID INTEGER NOT NULL, adresses_ID INTEGER NOT NULL, PRIMARY KEY (Client_ID, adresses_ID))

INSERT INTO ADRESSE (ID, CP, NUM,PAYS,VOIE,VOIETYPE) VALUES (1000, '60000',1, 'FRANCE','lala', 'rue')
INSERT INTO ITEM (ID,LABEL,SIZE,WEIGHT) VALUES (1001,'Ordinateur',30,200)